{
  "uid" : "b718b0d3ac1cc622",
  "name" : "test_home",
  "fullName" : "tests.test_suit2.test_demo2.Test_demo#test_home",
  "historyId" : "664876ab20be2b5ad5a0349406424ad4",
  "time" : {
    "start" : 1658393619252,
    "stop" : 1658393639601,
    "duration" : 20349
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driverenv",
    "time" : {
      "start" : 1658393608682,
      "stop" : 1658393619249,
      "duration" : 10567
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "caserun",
    "time" : {
      "start" : 1658393619250,
      "stop" : 1658393619250,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "action",
    "time" : {
      "start" : 1658393619250,
      "stop" : 1658393619250,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "46505a8dbba6dea6",
      "name" : "log",
      "source" : "46505a8dbba6dea6.txt",
      "type" : "text/plain",
      "size" : 1315
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "caserun::0",
    "time" : {
      "start" : 1658393639602,
      "stop" : 1658393642290,
      "duration" : 2688
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "c766629a5cc2fe64",
      "name" : "用例结束前的截图_16:54:02_.png",
      "source" : "c766629a5cc2fe64.png",
      "type" : "image/png",
      "size" : 2072325
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1
  }, {
    "name" : "action::0",
    "time" : {
      "start" : 1658393642311,
      "stop" : 1658393642803,
      "duration" : 492
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.test_suit2"
  }, {
    "name" : "suite",
    "value" : "test_demo2"
  }, {
    "name" : "subSuite",
    "value" : "Test_demo"
  }, {
    "name" : "host",
    "value" : "DESKTOP-QR6KK6V"
  }, {
    "name" : "thread",
    "value" : "22108-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_suit2.test_demo2"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "6313f3e238b4705b",
      "status" : "passed",
      "time" : {
        "start" : 1658393519305,
        "stop" : 1658393539599,
        "duration" : 20294
      }
    }, {
      "uid" : "ba8991c64edf68e",
      "status" : "passed",
      "time" : {
        "start" : 1658393471604,
        "stop" : 1658393495840,
        "duration" : 24236
      }
    }, {
      "uid" : "24912a6659c7bad7",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.testfairy.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.testfairy.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658393229189,
        "stop" : 1658393229189,
        "duration" : 0
      }
    }, {
      "uid" : "b40c40161b8632c1",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658393143371,
        "stop" : 1658393143371,
        "duration" : 0
      }
    }, {
      "uid" : "531ce154c530a85d",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658393103705,
        "stop" : 1658393103705,
        "duration" : 0
      }
    }, {
      "uid" : "3768d608b268d297",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install -g D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl59834376.tmp/base.apk]\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install -g D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl59834376.tmp/base.apk]\r\n\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658393038750,
        "stop" : 1658393038750,
        "duration" : 0
      }
    }, {
      "uid" : "63d02b0a4d9f6dd5",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1375721443.tmp/base.apk]\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1375721443.tmp/base.apk]\r\n\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658392911674,
        "stop" : 1658392911674,
        "duration" : 0
      }
    }, {
      "uid" : "ba72ee27a5c44733",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl182528647.tmp/base.apk]\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl182528647.tmp/base.apk]\r\n\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658392121372,
        "stop" : 1658392121372,
        "duration" : 0
      }
    }, {
      "uid" : "69fb660887212c83",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl2027787059.tmp/base.apk]\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\adt-bundle-windows-x86_64-20140702\\\\sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 98899a355358495654 install D:\\\\Users\\\\Mika\\\\PycharmProjects\\\\py_appauto\\\\data\\\\apk\\\\qooapp-v8.3.15-fairytest.apk' exited with code 1'; Command output: adb: failed to install D:\\Users\\Mika\\PycharmProjects\\py_appauto\\data\\apk\\qooapp-v8.3.15-fairytest.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl2027787059.tmp/base.apk]\r\n\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658391794282,
        "stop" : 1658391794282,
        "duration" : 0
      }
    }, {
      "uid" : "b091993eaf94ee64",
      "status" : "broken",
      "statusDetails" : "base.verify.NotFoundElementError",
      "time" : {
        "start" : 1658387302073,
        "stop" : 1658387316186,
        "duration" : 14113
      }
    }, {
      "uid" : "f972cbcc09a6657a",
      "status" : "passed",
      "time" : {
        "start" : 1658386734913,
        "stop" : 1658386754981,
        "duration" : 20068
      }
    }, {
      "uid" : "d43e7d5aa2b9d7ad",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B218DDA20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1658385972692,
        "stop" : 1658385972692,
        "duration" : 0
      }
    }, {
      "uid" : "7db3cfa112fd01d7",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'SearchListPage' object has no attribute '第一个商品项'",
      "time" : {
        "start" : 1658385907510,
        "stop" : 1658385913063,
        "duration" : 5553
      }
    }, {
      "uid" : "8aeabf2dcec7f5c7",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'SearchListPage' object has no attribute '第一个商品项'",
      "time" : {
        "start" : 1658384932038,
        "stop" : 1658384937304,
        "duration" : 5266
      }
    }, {
      "uid" : "dfb5af57bc4f4a46",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'SearchListPage' object has no attribute '第一个商品项'",
      "time" : {
        "start" : 1658384064032,
        "stop" : 1658384070783,
        "duration" : 6751
      }
    }, {
      "uid" : "8ae6bdb89a41b6f1",
      "status" : "broken",
      "statusDetails" : "base.verify.NotFoundElementError",
      "time" : {
        "start" : 1658384015189,
        "stop" : 1658384020573,
        "duration" : 5384
      }
    }, {
      "uid" : "f149e6d0e7897da9",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'SearchListPage' object has no attribute '第一个商品项'",
      "time" : {
        "start" : 1658316314706,
        "stop" : 1658316320184,
        "duration" : 5478
      }
    }, {
      "uid" : "36f417365cc60972",
      "status" : "broken",
      "statusDetails" : "base.verify.NotFoundElementError",
      "time" : {
        "start" : 1658316241940,
        "stop" : 1658316249269,
        "duration" : 7329
      }
    }, {
      "uid" : "e01e34e5166b3402",
      "status" : "broken",
      "statusDetails" : "base.verify.NotFoundElementError",
      "time" : {
        "start" : 1658316214093,
        "stop" : 1658316219341,
        "duration" : 5248
      }
    }, {
      "uid" : "b8b1be63f1ae380d",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'D://Users//Mika//PycharmProjects//appauto//data//apk//jumei.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'D://Users//Mika//PycharmProjects//appauto//data//apk//jumei.apk' does not exist or is not accessible\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658316128719,
        "stop" : 1658316128719,
        "duration" : 0
      }
    }, {
      "uid" : "4547857e7743d12f",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/Mika/PycharmProjects/appauto/data/apk/jumei.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/Mika/PycharmProjects/appauto/data/apk/jumei.apk' does not exist or is not accessible\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)",
      "time" : {
        "start" : 1658316055330,
        "stop" : 1658316055330,
        "duration" : 0
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "b718b0d3ac1cc622.json",
  "parameterValues" : [ ]
}